---
title: Scrumbled Eggs - PoE 2017
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: evan@new-schmidt.com
description: The website of team Scrumbled Eggs for the Principles of Engineering
  course at Olin College of Engineering in Fall 2017. Currently investigating the
  intersection of whiteboards and Computer Numerical Control.
baseurl: ''
url: https://scrumbledeggs.github.io
github_username: scrumbledeggs
markdown: kramdown
theme: minima
plugins:
- jekyll-feed
