---
title: BoardBot
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  sprints:
    title: Sprints
    output: true
    permalink: sprints/:title/
  uploads:
    title: Uploads
    output: true
subtitle: Olin PoE 2017
email: evan@new-schmidt.com
description: 'The website of team Scrumbled Eggs for the Principles of Engineering
  course at Olin College of Engineering in Fall 2017. Currently investigating the
  intersection of whiteboards and Computer Numerical Control.

'
street_address: 1000 Olin Way
city: Needham
state: MA
zip_code: '02492'
country: United States of America
url: https://scrumbledeggs.github.io/
github_url: https://github.com/scrumbledeggs
google_analytics: UA-110661156-1
markdown: kramdown
plugins:
- jekyll-feed
